on:
  pull_request:
  push:
    branches: [master]

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: flutter format -l 120 --set-exit-if-changed .

  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.0'
          channel: 'stable'
      - name: install dependencies
        working-directory: ./tourou
        run: flutter pub get
      - name: analyze
        run: flutter analyze --no-fatal-infos --fatal-warnings .

